approvals:
  minimum: 2              
  pattern: "^(:\\+1:|👍|approved)$"   
  veto:
    pattern: "^(:\\-1:|👎|rejected)$" 
  from:
    collaborators: true
commit:
  message:
    patterns:
      - "^(feat|fix|docs|style|refactor|perf|test|chore)(|\\([a-zA-Z0-9-._]+\\)):.{3,}"
